//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP41.Cumponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hardware()
        {
            this.HardwareImage = new HashSet<HardwareImage>();
            this.ProductHardware = new HashSet<ProductHardware>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual HardwareType HardwareType { get; set; }
        public virtual HardwareUnit HardwareUnit { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HardwareImage> HardwareImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHardware> ProductHardware { get; set; }
    }
}
