//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP41.Cumponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public int IdWorkshop { get; set; }
        public int IdItem { get; set; }
        public Nullable<decimal> FromLeft { get; set; }
        public Nullable<decimal> FromUp { get; set; }
    
        public virtual WorkshopItem WorkshopItem { get; set; }
        public virtual WorkshopItem WorkshopItem1 { get; set; }
    }
}
