//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP41.Cumponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOperation
    {
        public int ProductId { get; set; }
        public string Description { get; set; }
        public int OrderCount { get; set; }
        public Nullable<System.TimeSpan> OperationTime { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Product Product { get; set; }
    }
}
