//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP41.Cumponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusOrder
    {
        public int Id { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdOldStatus { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public Nullable<System.TimeSpan> TimeChange { get; set; }
        public string OrderNumber { get; set; }
        public string Description { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
    }
}
